### ISSUE TITLE
Feedback 09-Sep-2020

### ISSUE THREAD

**Issue by Al-un** [oFrederic/Budgety#1]
Pour le moment, c'est propre je trouve :)

### `index.html`

I didn't know about the `async` attribute there:

```html
<script src="app.js" async></script>
```

I was used to the old fashioned way of putting `<script src="app.js" async></script>` at the end of the HTML document. Do you know why it is necessary? or why the `async` attribute is necessary?

### `app.js`

**UI Controller**

I assume that this page will only have one input (adding a budget entry). However, for the sake of clarity, I suggest a less generic naming convention. For example:

```diff
-    getInput: function () {
+    getNewBudgetEntry: function () {
      return {
-        input: document.querySelector(this.DOMstring.inputType).value, // inc or exp (+ or -)
+        type: document.querySelector(this.DOMstring.inputType).value, // inc or exp (+ or -)
        description: document.querySelector(this.DOMstring.inputDescription)
          .value,
-        value: document.querySelector(this.DOMstring.inputValue).value,
+        amount: document.querySelector(this.DOMstring.inputValue).value,
      };
    },
```

When calling the UI controller, the call would look like `UIController.getNewBudgetEntry().amount` instead of `UIController.getInput().value`.

Any renaming of `getInput()` should also imply a renaming of entries with `DOMstring`.

**Controller**

You might need to check if description and amount are not empty, unless if those checks are done in `ctrlAddItem`:

```js
document.addEventListener("keypress", function (event) {
  if (event.key === "Enter") ctrlAddItem();
});
```

In terms of "responsibilities", you have two options:

1. Check if the inputs, from the UIController, are correct and proceed if appropriate
2. Add a flag in the UIController such as `isNewBudgetEntryValid()` which would return `true` if the form can be processed.

Both approaches have the same result but the vision is slightly different. I don't have a preference as it can become situational. As this project is quite small, it does not really matter.

**Comment by oFrederic** [comment]
The best practice would want to put the `<script src="app.js"></script>` in the `<head>` and use `async` or `defer`. 

`async` will load at the same time as your HTML without blocking your browser and `defer` will load it once your HTML its already loaded.
